name: build

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the addon
        run: ./build_xpi.sh
      - name: Archive the build result
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-export-addon
          path: obsidian-export.xpi
